weights: yolov5s.pt
cfg: models/yolov5s.yaml
data: data/coco.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 100
batch_size: 16
img_size:
- 640
- 480
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 4
project: runs/train
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
log_imgs: 16
log_artifacts: false
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/exp2
